version: appvayor.{build}

clone_folder: c:\dev\superimpose-mesh-lib

cache:
  - 'C:\Tools\vcpkg\installed\'

environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      CMAKE_GENERATOR: "Visual Studio 14 2015"
      VCPKG_TRIPLET_NAME: "x86-windows"
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      CMAKE_GENERATOR: "Visual Studio 14 2015 Win64"
      VCPKG_TRIPLET_NAME: "x64-windows"
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      CMAKE_GENERATOR: "Visual Studio 15 2017"
      VCPKG_TRIPLET_NAME: "x86-windows"
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      CMAKE_GENERATOR: "Visual Studio 15 2017 Win64"
      VCPKG_TRIPLET_NAME: "x64-windows"

configuration:
  - Release
  - Debug

init:
  # Print some more system information after installing all build tools
  - ps: echo "-------------------- BEGIN SYSTEM INFORMATION --------------------"
  - ps: echo CMAKE_GENERATOR=$env:CMAKE_GENERATOR
  - ps: echo VCPKG_TRIPLET_NAME=$env:VCPKG_TRIPLET_NAME
  - ps: cmake --version
  - ps: git config --global core.autocrlf input
  - ps: echo CONFIGURATION=$env:CONFIGURATION
  - ps: echo "--------------------  END SYSTEM INFORMATION  --------------------"

install:
  - ps: cd c:\dev
  - git clone https://github.com/robotology/ycm.git
  - ps: cd ycm
  - git checkout devel
  - ps: mkdir build
  - ps: cd build
  - ps: cmake -G "$env:CMAKE_GENERATOR" -DCMAKE_INSTALL_PREFIX:PATH=c:\dev\install ..
  - ps: cmake --build . --target INSTALL --config $env:CONFIGURATION
  - ps: $env:YCM_DIR="c:\dev\install\share\YCM\cmake"
  - ps: cd c:\dev
  - ps: vcpkg install assimp:$env:VCPKG_TRIPLET_NAME
  - ps: vcpkg install glfw3:$env:VCPKG_TRIPLET_NAME
  - ps: vcpkg install glew:$env:VCPKG_TRIPLET_NAME
  - ps: vcpkg install glm:$env:VCPKG_TRIPLET_NAME
  - ps: vcpkg install opencv:$env:VCPKG_TRIPLET_NAME
  - ps: vcpkg list

build:

build_script:
  - ps: cd c:\dev\superimpose-mesh-lib
  - ps: mkdir build
  - ps: cd build
  - ps: cmake -G "$env:CMAKE_GENERATOR" -DCMAKE_TOOLCHAIN_FILE=c:/Tools/vcpkg/scripts/buildsystems/vcpkg.cmake -DBUILD_TESTING:BOOL=ON ..
  - ps: cmake --build . --target ALL_BUILD --config $env:CONFIGURATION

after_build:

test_script:
  - ps: cd c:\dev\superimpose-mesh-lib\build
  - ps: ctest -N
